# Generated by Django 4.1.7 on 2023-03-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomApp', models.CharField(max_length=200, unique=True)),
                ('UrlApp', models.CharField(max_length=200, null=True)),
                ('Datecreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Lastname', models.CharField(max_length=200)),
                ('Role', models.CharField(max_length=200)),
                ('Note', models.TextField(null=True)),
                ('Datecreation', models.DateTimeField(auto_now_add=True)),
                ('field', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('image', models.ImageField(default=None, null=True, upload_to='uploads/image')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=200, unique=True)),
                ('Etat', models.BooleanField()),
                ('Datecreation', models.DateTimeField(auto_now_add=True)),
                ('IdApp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generateurpassword.app')),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generateurpassword.user')),
            ],
            options={
                'unique_together': {('IdUser', 'IdApp')},
            },
        ),
    ]
