FROM python:3.8

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV MYSQL_DATABASE=paiperleck
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=true
ENV MYSQL_HOST=localhost
ENV MYSQL_PORT=3306

# Install the MySQL client library
RUN apt-get update && \
    apt-get install -y default-libmysqlclient-dev && \
    apt-get install -y mysql-server && \
    service mysql start \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the requirements file and install the dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port that the application will be running on
EXPOSE 8000

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
